name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? How can the issue be reproduced?
      description: Please describe the issue in as much detail as possible.
      placeholder: If possible, please include a screenshot or video of the issue in action!
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform did you experience the bug on?
      options:
        - Web Demo
        - Windows Demo
        - Mac Demo
        - Linux Demo
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of the game were you playing?
      description: You can find the version number in the lower-left corner of the title screen.
      placeholder: (e.g. 0.35.1)
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Unity Player Log output
      description: Please copy and paste any relevant log output from the **Unity player log** (see directions below).
      placeholder: (see below instructions on where to find this)
      render: shell
  - type: markdown
    attributes:
      value: |
        ## How to find Unity player logs
        Unity outputs logs to a specific file which is created every time you run the game. This often has relevant information that will help debug the issue.
        
        | Platform | File Location |
        | --- | --- |
        | Windows | `%USERPROFILE%\AppData\LocalLow\DDRKirby(ISQ)\Rhythm Quest\Player.log`. |
        | Mac | `~/Library/Logs/DDRKirby(ISQ)/Rhythm Quest/Player.log` |
        | Linux | `~/.config/unity3d/DDRKirby(ISQ)/Rhythm Quest/Player.log` |
        | Web | Check the browser console (usually by pressing `F12` and clicking on the "Console" tab). |
        
        The `Player.log` file is recreated from scratch every time the game runs. The previous run can be found at `Player-prev.log` in the same directory.
