name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: If possible, please include a screenshot or video of the issue in action!
      placeholder: Please describe the issue in as much detail as possible.
    validations:
      required: true
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What version of the game did you experience the bug on?
      options:
        - Web Demo
        - Windows Demo
        - Mac Demo
        - Linux Demo
      default: 0
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What version of the game were you playing?
      description: You can find the version number in the lower-left corner of the title screen.
      placeholder: e.g. 0.35.1
  - type: markdown
    attributes:
      value: |
        arst
        How to find Unity player logs:
        On **Windows**: navigate to `%USERPROFILE%\AppData\LocalLow\DDRKirby(ISQ)\Rhythm Quest\Player.log`
        On **Mac**: you can find this at `~/Library/Logs/DDRKirby(ISQ)/Rhythm Quest/Player.log`
        On **Linux**: the log is at `~/.config/unity3d/DDRKirby(ISQ)/Rhythm Quest/Player.log
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
